openapi: 3.0.1
info:
  title: MessageAPI
  description: API Definition of MessageAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/messageapi
- url: https://localhost:8253/messageapi
paths:
  /parse:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /store:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
